import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Link from "next/link";
import Providers from "./providers";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comments App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubik.className}>
      <Providers>
      {children}
      </Providers>
       </body>
    </html>
  );
}
